version: '3'

services:
  dev_server:
    build:
      context: .
      dockerfile: docker/demo/devserver.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - node_server
    volumes:
      - ./env/fullchain.pem:/app/env/fullchain.pem
      - ./env/privkey.pem:/app/env/privkey.pem
      
  node_server:
    build:
      context: .
      dockerfile: docker/demo/nodeserver.Dockerfile
    expose:
      - "5000"

  mongo:
    image: "mongo:latest"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
