version: '3'

services:
  dev_server:
    build:
      context: .
      dockerfile: docker/demo/devserver.Dockerfile
    ports:
      - "7000:80"
    depends_on:
      - redis
      - mongo
      
  node_server:
    build:
      context: .
      dockerfile: docker/demo/nodeserver.Dockerfile
    ports:
      - "7001:80"

  redis:
    image: "redis:latest"

  mongo:
    image: "mongo:latest"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
